#cloud-config

groups:
- docker

users:
- default
- name: qserv
  gecos: "Qserv user"
  groups: docker
  lock-passwd: true
  shell: /bin/bash
  sudo: "ALL=(ALL) NOPASSWD:ALL"

package_upgrade: true

packages:
- nmap-ncat
- git

runcmd:
- 'sudo -u qserv bash -c "cd /home/qserv && git clone https://github.com/lsst/qserv.git src/qserv"' 

