#cloud-config

groups:
- docker

users:
- default
- name: qserv
  gecos: "Qserv user"
  groups: docker
  lock-passwd: true
  shell: /bin/bash
  sudo: "ALL=(ALL) NOPASSWD:ALL"

package_upgrade: true

packages:
# Install epel directory first to enable
# some packages installation (like byobu)
- epel-release
- cmake
- docker
- gcc
- gcc-c++
- golang
- lsof
- git
- nmap-ncat
- python-devel
- telnet
- vim
- zsh

runcmd:
# Install EPEL packages
- 'sudo yum install byobu htop'
  # Disable SELinux
- 'setenforce 0'
- 'sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/sysconfig/selinux'
- 'su -c "cd /home/qserv && git clone https://github.com/lsst/qserv.git src/qserv" qserv'
- 'su -c "cd /home/qserv/src && git clone https://github.com/fjammes/dot-config.git" qserv'
- 'systemctl start docker'
- 'su -c "docker pull qserv/qserv:dev" qserv'
- 'su -c "/home/qserv/src/qserv/admin/tools/docker/3_build-git-image.sh -R tickets/DM-13979" qserv'
- 'su -c "cd /home/qserv/src/dot-config && ./configure.sh" qserv'

