# See http://docs.openstack.org/developer/heat/template_guide/hot_spec.html

heat_template_version: 2015-04-30

description: Launch Qserv build node 

parameters:
    prefix:
        description: Resource prefix
        label: Resource prefix
        type: string
    key_name:
        description: Name of an existing key pair to use for the instance
        label: Key Name
        type: string
        constraints:
            - custom_constraint: nova.keypair
    flavor:
        description: Flavor for build node
        label: Flavor ID
        type: string
    image_id:
        description: UUID of source image
        label: Image ID
        type: string
    network_name:
        description: Name of the network to connect to
        label: Network Name
        type: string
        constraints:
            - custom_constraint: neutron.network
    subnet_name:
        description: Name of the subnet to connect to
        label: Subnet Name
        type: string
        constraints:
            - custom_constraint: neutron.subnet
    ssh_security_group:
        description: Name of SSH security group
        label: SSH security group
        type: string

resources:
    floating_ip:
        type: OS::Nova::FloatingIP
        properties:
            pool: ext-net
    instance:
        type: OS::Nova::Server
        properties:
            key_name: { get_param: key_name }
            flavor: { get_param: flavor }
            image: { get_param: image_id }
            name: fjammes-qserv-build

            networks:
                - port: { get_resource: port }
            user_data: { get_file: cloud-config.yaml }
            user_data_format: RAW
    port:
        type: OS::Neutron::Port
        properties:
            network: { get_param: network_name }
            fixed_ips:
                - subnet_id: { get_param: subnet_name }
            security_groups:
                - { get_param: ssh_security_group }
    association:
        type: OS::Nova::FloatingIPAssociation
        properties:
            floating_ip: { get_resource: floating_ip }
            server_id: { get_resource: instance }

outputs:
    instance_public_ip:
        description: Floating IP address of instance in public network
        value: { get_attr: [ floating_ip, ip] }
# EOF
